import { Category, Course, Event } from '@/types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Computer Science', icon: 'laptop-outline', color: '#4A90E2' },
  { id: '2', name: 'Engineering', icon: 'construct-outline', color: '#E94B3C' },
  { id: '3', name: 'Business', icon: 'briefcase-outline', color: '#50C878' },
  { id: '4', name: 'Arts & Design', icon: 'color-palette-outline', color: '#F39C12' },
  { id: '5', name: 'Science', icon: 'flask-outline', color: '#9B59B6' },
  { id: '6', name: 'Mathematics', icon: 'calculator-outline', color: '#3498DB' },
];

export const COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Mobile Application Development',
    description: 'Learn to build native mobile applications using React Native and Expo. This comprehensive course covers everything from basic components to advanced state management and API integration.',
    category: 'Computer Science',
    instructor: 'Dr. Sarah Johnson',
    duration: '12 weeks',
    level: 'Intermediate',
    rating: 4.8,
    enrolledCount: 245,
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
    startDate: '2024-01-15',
    endDate: '2024-04-07',
    location: 'Online',
    price: 0,
    tags: ['React Native', 'Mobile Dev', 'TypeScript'],
  },
  {
    id: 'c2',
    title: 'Data Structures and Algorithms',
    description: 'Master fundamental data structures and algorithms essential for technical interviews and software engineering. Includes practical problem-solving sessions.',
    category: 'Computer Science',
    instructor: 'Prof. Michael Chen',
    duration: '10 weeks',
    level: 'Intermediate',
    rating: 4.9,
    enrolledCount: 320,
    thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400',
    startDate: '2024-02-01',
    endDate: '2024-04-12',
    location: 'CS Building - Room 301',
    price: 0,
    tags: ['DSA', 'Algorithms', 'Problem Solving'],
  },
  {
    id: 'c3',
    title: 'Web Development Bootcamp',
    description: 'Full-stack web development course covering HTML, CSS, JavaScript, React, Node.js, and MongoDB. Build real-world projects and deploy them.',
    category: 'Computer Science',
    instructor: 'Dr. Emily Rodriguez',
    duration: '16 weeks',
    level: 'Beginner',
    rating: 4.7,
    enrolledCount: 410,
    thumbnail: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=400',
    startDate: '2024-01-20',
    endDate: '2024-05-15',
    location: 'Online',
    price: 0,
    tags: ['Web Dev', 'Full Stack', 'JavaScript'],
  },
  {
    id: 'c4',
    title: 'Machine Learning Fundamentals',
    description: 'Introduction to machine learning concepts, algorithms, and practical applications using Python and popular ML libraries.',
    category: 'Computer Science',
    instructor: 'Dr. David Kim',
    duration: '14 weeks',
    level: 'Advanced',
    rating: 4.9,
    enrolledCount: 189,
    thumbnail: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400',
    startDate: '2024-02-10',
    endDate: '2024-05-20',
    location: 'AI Lab - Building 5',
    price: 0,
    tags: ['ML', 'AI', 'Python'],
  },
  {
    id: 'c5',
    title: 'Digital Marketing Strategy',
    description: 'Learn modern digital marketing techniques including SEO, social media marketing, content strategy, and analytics.',
    category: 'Business',
    instructor: 'Prof. Amanda Foster',
    duration: '8 weeks',
    level: 'Beginner',
    rating: 4.6,
    enrolledCount: 275,
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    startDate: '2024-01-25',
    endDate: '2024-03-22',
    location: 'Business School - Room 105',
    price: 0,
    tags: ['Marketing', 'SEO', 'Social Media'],
  },
  {
    id: 'c6',
    title: 'UI/UX Design Principles',
    description: 'Master the fundamentals of user interface and user experience design. Learn design thinking, prototyping, and usability testing.',
    category: 'Arts & Design',
    instructor: 'Ms. Jessica Williams',
    duration: '10 weeks',
    level: 'Beginner',
    rating: 4.8,
    enrolledCount: 198,
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400',
    startDate: '2024-02-05',
    endDate: '2024-04-16',
    location: 'Design Studio - Building 3',
    price: 0,
    tags: ['UI/UX', 'Design', 'Figma'],
  },
  {
    id: 'c7',
    title: 'Robotics and Automation',
    description: 'Hands-on course in robotics covering sensors, actuators, control systems, and programming autonomous robots.',
    category: 'Engineering',
    instructor: 'Dr. Robert Martinez',
    duration: '12 weeks',
    level: 'Advanced',
    rating: 4.7,
    enrolledCount: 142,
    thumbnail: 'https://images.unsplash.com/photo-1563207153-f403bf289096?w=400',
    startDate: '2024-02-15',
    endDate: '2024-05-10',
    location: 'Engineering Lab - Room 201',
    price: 0,
    tags: ['Robotics', 'Automation', 'IoT'],
  },
  {
    id: 'c8',
    title: 'Quantum Computing Basics',
    description: 'Introduction to quantum computing principles, quantum algorithms, and their applications in solving complex problems.',
    category: 'Computer Science',
    instructor: 'Prof. Lisa Anderson',
    duration: '8 weeks',
    level: 'Advanced',
    rating: 4.9,
    enrolledCount: 98,
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400',
    startDate: '2024-03-01',
    endDate: '2024-04-26',
    location: 'Physics Building - Room 405',
    price: 0,
    tags: ['Quantum', 'Computing', 'Physics'],
  },
];

export const EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'Tech Career Fair 2024',
    description: 'Annual technology career fair featuring top tech companies and startups. Network with recruiters, attend workshops, and explore career opportunities.',
    category: 'Career',
    date: '2024-03-15',
    time: '10:00 AM - 4:00 PM',
    location: 'Main Campus Hall',
    organizer: 'Career Services',
    capacity: 500,
    registered: 342,
    thumbnail: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400',
    tags: ['Career', 'Networking', 'Tech'],
    isOnline: false,
  },
  {
    id: 'e2',
    title: 'Hackathon: Build for Change',
    description: '24-hour hackathon focused on creating innovative solutions for social and environmental challenges. Win prizes and make an impact!',
    category: 'Competition',
    date: '2024-02-20',
    time: '9:00 AM',
    location: 'Innovation Center',
    organizer: 'Computer Science Society',
    capacity: 150,
    registered: 127,
    thumbnail: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400',
    tags: ['Hackathon', 'Coding', 'Competition'],
    isOnline: false,
  },
  {
    id: 'e3',
    title: 'AI & Ethics Symposium',
    description: 'Join leading experts in discussing the ethical implications of AI, including bias, privacy, and responsible AI development.',
    category: 'Workshop',
    date: '2024-02-28',
    time: '2:00 PM - 5:00 PM',
    location: 'Zoom Webinar',
    organizer: 'AI Research Lab',
    capacity: 1000,
    registered: 645,
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400',
    tags: ['AI', 'Ethics', 'Research'],
    isOnline: true,
  },
  {
    id: 'e4',
    title: 'Startup Pitch Competition',
    description: 'Watch student entrepreneurs pitch their startup ideas to a panel of investors and industry experts. Network with the entrepreneurial community.',
    category: 'Competition',
    date: '2024-03-10',
    time: '6:00 PM - 9:00 PM',
    location: 'Business School Auditorium',
    organizer: 'Entrepreneurship Club',
    capacity: 200,
    registered: 156,
    thumbnail: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=400',
    tags: ['Startup', 'Entrepreneurship', 'Business'],
    isOnline: false,
  },
  {
    id: 'e5',
    title: 'Web3 and Blockchain Workshop',
    description: 'Learn about blockchain technology, smart contracts, and decentralized applications. Hands-on session with real-world examples.',
    category: 'Workshop',
    date: '2024-02-25',
    time: '1:00 PM - 4:00 PM',
    location: 'CS Building - Lab 402',
    organizer: 'Blockchain Club',
    capacity: 80,
    registered: 73,
    thumbnail: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400',
    tags: ['Blockchain', 'Web3', 'Crypto'],
    isOnline: false,
  },
  {
    id: 'e6',
    title: 'Design Thinking Bootcamp',
    description: 'Interactive workshop on design thinking methodology. Learn to solve complex problems through human-centered design.',
    category: 'Workshop',
    date: '2024-03-05',
    time: '10:00 AM - 3:00 PM',
    location: 'Innovation Hub',
    organizer: 'Design School',
    capacity: 50,
    registered: 48,
    thumbnail: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=400',
    tags: ['Design', 'Innovation', 'Workshop'],
    isOnline: false,
  },
  {
    id: 'e7',
    title: 'Cybersecurity Summit',
    description: 'Annual cybersecurity event featuring talks on latest security threats, defense strategies, and hands-on CTF challenges.',
    category: 'Conference',
    date: '2024-03-20',
    time: '9:00 AM - 5:00 PM',
    location: 'Conference Center',
    organizer: 'Security Research Group',
    capacity: 300,
    registered: 267,
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400',
    tags: ['Security', 'Cybersecurity', 'CTF'],
    isOnline: false,
  },
  {
    id: 'e8',
    title: 'Women in Tech Panel',
    description: 'Inspiring panel discussion with successful women leaders in technology sharing their experiences and career advice.',
    category: 'Panel',
    date: '2024-03-08',
    time: '5:00 PM - 7:00 PM',
    location: 'Student Center Theater',
    organizer: 'Women in STEM',
    capacity: 250,
    registered: 189,
    thumbnail: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=400',
    tags: ['Women in Tech', 'Panel', 'Inspiration'],
    isOnline: false,
  },
];
